<a href="https://colab.research.google.com/github/imhasib777/Data-Analysis-projects-using-Python/blob/main/Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Datasets/all_data.csv")

In [6]:
df.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"

In [7]:
df.columns

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')

###1. Removing NAN value

In [8]:
nan_values=df[df.isna().any(axis=1)]
nan_values

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,NaN,NaN,NaN,NaN,NaN
735,NaN,NaN,NaN,NaN,NaN,NaN
1433,NaN,NaN,NaN,NaN,NaN,NaN
1553,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
185176,NaN,NaN,NaN,NaN,NaN,NaN
185438,NaN,NaN,NaN,NaN,NaN,NaN
186042,NaN,NaN,NaN,NaN,NaN,NaN
186548,NaN,NaN,NaN,NaN,NaN,NaN
186826,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df=df.dropna(how="any")
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [10]:
nan_values=df[df.isna().any(axis=1)]
nan_values

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Purchase Address]
Index: []

###So all the nan values are removed

In [11]:
df=df[df["Order Date"].str[0:2]!="Or"]

# **2. Creating  a new column "City"**

In [12]:
df["City_name"]=df["Purchase Address"].str.split(",").str[1]
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles

#**3. Creating a new column City-State**

In [13]:
df["City-State"]=df["Purchase Address"].str.split(",").str[1]+" "+df["Purchase Address"].str.split(",").str[2]
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name,City-State
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas,Dallas TX 75001
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston,Boston MA 02215
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001

#**4. Creating a month column**

In [14]:
df["Month"]=df["Order Date"].str[0:2]
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name,City-State,Month
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas,Dallas TX 75001,04
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston,Boston MA 02215,04
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,04
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,04
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,04

#**5. Replacing the value of "month" column with month name**

In [15]:
df["Month"]=df["Month"].replace(["01","02","03","04","05","06","07","08","09","10","11","12"],["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])

In [16]:
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name,City-State,Month
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas,Dallas TX 75001,Apr
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston,Boston MA 02215,Apr
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr

#**6. Adding "sales" column**

In [17]:
df["Quantity Ordered"]=pd.to_numeric(df["Quantity Ordered"])
df["Price Each"]=pd.to_numeric(df["Price Each"])
df["Sales"]=df["Quantity Ordered"]*df["Price Each"]
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name,City-State,Month,Sales
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas,Dallas TX 75001,Apr,23.90
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston,Boston MA 02215,Apr,99.99
3,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,600.00
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,11.99
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,11.99

#**7. What city sold the most product in the whole year?**

In [18]:
c=df.groupby("City_name").sum()["Sales"].sort_values(ascending=False)
c

City_name
 San Francisco    8262203.91
 Los Angeles      5452570.80
 New York City    4664317.43
 Boston           3661642.01
 Atlanta          2795498.58
 Dallas           2767975.40
 Seattle          2747755.48
 Portland         2320490.61
 Austin           1819581.75
Name: Sales, dtype: float64

In [19]:
c.head(1)

City_name
 San Francisco    8262203.91
Name: Sales, dtype: float64

#**8. What sate sold the most product?**

In [20]:
cs=df.groupby("City-State").sum()["Sales"].sort_values(ascending=False)
cs

City-State
 San Francisco  CA 94016    8262203.91
 Los Angeles  CA 90001      5452570.80
 New York City  NY 10001    4664317.43
 Boston  MA 02215           3661642.01
 Atlanta  GA 30301          2795498.58
 Dallas  TX 75001           2767975.40
 Seattle  WA 98101          2747755.48
 Portland  OR 97035         1870732.34
 Austin  TX 73301           1819581.75
 Portland  ME 04101          449758.27
Name: Sales, dtype: float64

In [21]:
cs.head(1)

City-State
 San Francisco  CA 94016    8262203.91
Name: Sales, dtype: float64

#**9. In every month which city has the most sell?**

In [22]:

df.loc[df.groupby('Month')['Sales'].idxmax(), ['Month', 'City_name', 'Sales']]

       Month       City_name    Sales
4717     Apr   San Francisco  3400.00
18392    Aug     Los Angeles  1700.00
30394    Dec   New York City  1700.00
55527    Feb   San Francisco  1700.00
76338    Jan   New York City  1999.98
77324    Jul          Boston  1700.00
92026    Jun   San Francisco  3400.00
105291   Mar     Los Angeles  1700.00
127265   May          Boston  3400.00
137142   Nov          Boston  1700.00
174998   Oct          Boston  1999.98
175218   Sep         Seattle  1700.00

#**10. Which month has the most sell?**

In [23]:
month=df.groupby("Month").sum()["Sales"].sort_values(ascending=False)
month

Month
Dec    4613443.34
Oct    3736726.88
Apr    3390670.24
Nov    3199603.20
May    3152606.75
Mar    2807100.38
Jul    2647775.76
Jun    2577802.26
Aug    2244467.88
Feb    2202022.42
Sep    2097560.13
Jan    1822256.73
Name: Sales, dtype: float64

In [24]:
month.head(1)

Month
Dec    4613443.34
Name: Sales, dtype: float64

#So the expected month is December

#**11. Adding Time(Hour) column**

In [25]:
df["Time(Hour)"]=df["Order Date"].str[9:11]
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,City_name,City-State,Month,Sales,Time(Hour)
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",Dallas,Dallas TX 75001,Apr,23.90,08
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",Boston,Boston MA 02215,Apr,99.99,22
3,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,600.00,14
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,11.99,14
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",Los Angeles,Los Angeles CA 90001,Apr,11.99,09

#**12. Which is the peak hour for sell (with respect to the whole year)?**

In [26]:
hour=df.groupby("Time(Hour)").sum()["Sales"].sort_values(ascending=False)
hour

Time(Hour)
19    2412938.54
12    2316821.34
11    2300610.24
20    2281716.24
18    2219348.30
13    2155389.80
17    2129361.61
14    2083672.73
21    2042000.86
10    1944286.77
15    1941549.60
16    1904601.31
09    1639030.58
22    1607549.21
08    1192348.97
23    1179304.44
07     744854.12
00     713721.27
01     460866.88
06     448113.00
02     234851.44
05     230679.82
04     162661.01
03     145757.89
Name: Sales, dtype: float64

In [27]:
hour.head(1)

Time(Hour)
19    2412938.54
Name: Sales, dtype: float64

#**19.00 to 19.59 is the peak time when  product sold the most.So this is the time when we should display advertisements.**

#**12. Which is the peak hour of selling products (In every month)?**

In [28]:
monthly_hourly_sales = df.groupby(['Month', 'Time(Hour)'])['Sales'].sum().reset_index()
peak_hour_per_month = monthly_hourly_sales.loc[monthly_hourly_sales.groupby('Month')['Sales'].idxmax()]
peak_hour_per_month

    Month Time(Hour)      Sales
19    Apr         19  249265.71
43    Aug         19  157582.13
67    Dec         19  323274.15
90    Feb         18  151569.22
108   Jan         12  134524.88
140   Jul         20  204422.41
163   Jun         19  181387.89
179   Mar         11  202886.61
204   May         12  237904.94
234   Nov         18  221210.45
252   Oct         12  274524.28
283   Sep         19  150576.47

#**13. What product sold the most in the whole year?**

In [29]:
p=df.groupby("Product").sum()["Quantity Ordered"].sort_values(ascending=False)
p

Product
AAA Batteries (4-pack)        31017
AA Batteries (4-pack)         27635
USB-C Charging Cable          23975
Lightning Charging Cable      23217
Wired Headphones              20557
Apple Airpods Headphones      15661
Bose SoundSport Headphones    13457
27in FHD Monitor               7550
iPhone                         6849
27in 4K Gaming Monitor         6244
34in Ultrawide Monitor         6199
Google Phone                   5532
Flatscreen TV                  4819
Macbook Pro Laptop             4728
ThinkPad Laptop                4130
20in Monitor                   4129
Vareebadd Phone                2068
LG Washing Machine              666
LG Dryer                        646
Name: Quantity Ordered, dtype: int64

In [30]:
p.head(1)

Product
AAA Batteries (4-pack)    31017
Name: Quantity Ordered, dtype: int64

#** AAA Batteries (4-pack) is the most sold product**

#**14. What product sold the most in every month?**

In [31]:
monthly_product_sales = df.groupby(['Month', 'Product'])["Quantity Ordered"].sum().reset_index()
peak_product_per_month = monthly_product_sales.loc[monthly_product_sales.groupby('Month')["Quantity Ordered"].idxmax()]
peak_product_per_month

    Month                 Product  Quantity Ordered
5     Apr  AAA Batteries (4-pack)              2939
24    Aug  AAA Batteries (4-pack)              2021
43    Dec  AAA Batteries (4-pack)              4241
62    Feb  AAA Batteries (4-pack)              1972
81    Jan  AAA Batteries (4-pack)              1600
100   Jul  AAA Batteries (4-pack)              2365
119   Jun  AAA Batteries (4-pack)              2162
138   Mar  AAA Batteries (4-pack)              2479
157   May  AAA Batteries (4-pack)              2927
176   Nov  AAA Batteries (4-pack)              3025
195   Oct  AAA Batteries (4-pack)              3363
214   Sep  AAA Batteries (4-pack)              1923